In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from money_tools import Mortgage

In [11]:
rate_config = {
            "rate": 0.01,
            "monthly_payment": 1000.00,
            "start_date": '2019-01-01',
            "term": None,
            "end_date": '2019-12-31',
            "payment_day": 1
        }

In [12]:
m = Mortgage(100_000, [rate_config])

In [13]:
m

Mortgage()

In [17]:
m.schedule.head()

,Date,Period,Begin Balance,Payment,Interest,Additional_Payment,End Balance,year,month,day,end_day,years_out,end_of_year_window
0,2019-01-01,1,100000.00,1000.0,2.74,0,99002.74,2019,1,1,31,0,0.0
1,2019-01-02,2,99002.74,0.0,2.71,0,99005.45,2019,1,2,31,0,0.0
2,2019-01-03,3,99005.45,0.0,2.71,0,99008.16,2019,1,3,31,0,0.0
3,2019-01-04,4,99008.16,0.0,2.71,0,99010.87,2019,1,4,31,0,0.0
4,2019-01-05,5,99010.87,0.0,2.71,0,99013.58,2019,1,5,31,0,0.0

In [10]:
m.rates

[Rate(start_balance=100000, annual_interest_rate=0.01, monthly_payment=1000.0, start_date='2019-01-01', end_date='2019-12-31')]

## Multi Rate Mortgage

In [26]:
rate_config1 = {
    "rate": 0.01,
    "monthly_payment": 1000.00,
    "start_date": '2019-01-01',
    "term": None,
    "end_date": '2019-12-31',
    "payment_day": 1
}

rate_config2 = {
    "rate": 0.02,
    "monthly_payment": 1000.00,
    "start_date": '2020-01-01',
    "term": None,
    "end_date": '2020-12-31',
    "payment_day": 1
}

In [30]:
m = Mortgage(100_000, [rate_config1, rate_config2])

In [31]:
m.schedule

,Date,Period,Begin Balance,Payment,Interest,Additional_Payment,End Balance,year,month,day,end_day,years_out,end_of_year_window
0,2019-01-01,1,100000.00,1000.0,2.74,0,99002.74,2019,1,1,31,0,0.0
1,2019-01-02,2,99002.74,0.0,2.71,0,99005.45,2019,1,2,31,0,0.0
2,2019-01-03,3,99005.45,0.0,2.71,0,99008.16,2019,1,3,31,0,0.0
3,2019-01-04,4,99008.16,0.0,2.71,0,99010.87,2019,1,4,31,0,0.0
4,2019-01-05,5,99010.87,0.0,2.71,0,99013.58,2019,1,5,31,0,0.0
5,2019-01-06,6,99013.58,0.0,2.71,0,99016.29,2019,1,6,31,0,0.0
6,2019-01-07,7,99016.29,0.0,2.71,0,99019.00,2019,1,7,31,0,0.0
7,2019-01-08,8,99019.00,0.0,2.71,0,99021.71,2019,1,8,31,0,0.0
8,2019-01-09,9,99021.71,0.0,2.71,0,99024.42,2019,1,9,31,0,0.0
9,2019-01-10,10,99024.42,0.0,2.71,0,99027.13,2019,1,10,31,0,0.0
10,2019-01-11,11,99027.13,0.0,2.71,0,99029.84,2019,1,11,31,0,0.0
11,2019-01-12,12,99029.84,0.0,2.71,0,99032.55,2019,1,12,31,0,0.0
12,2019-01-13,13,99032.55,0.0,2.71,0,99035.26,2019,1,13,31,0,0.0
13,2019-01-14,14,99035.26,0.0,2.71,0,99037.97,2019,1,14,31,0,0.0
14,2019-01-15,15,99037.97,0.0,2.71,0,99040.68,2019,1,15,31,0,0.0
15,2019-01-16,16,99040.68,0.0,2.71,0,99043.39,2019,1,16,31,0,0.0
16,2019-01-17,17,99043.39,0.0,2.71,0,99046.10,2019,1,17,31,0,0.0
17,2019-01-18,18,99046.10,0.0,2.71,0,99048.81,2019,1,18,31,0,0.0
18,2019-01-19,19,99048.81,0.0,2.71,0,99051.52,2019,1,19,31,0,0.0
19,2019-01-20,20,99051.52,0.0,2.71,0,99054.23,2019,1,20,31,0,0.0
20,2019-01-21,21,99054.23,0.0,2.71,0,99056.94,2019,1,21,31,0,0.0
21,2019-01-22,22,99056.94,0.0,2.71,0,99059.65,2019,1,22,31,0,0.0
22,2019-01-23,23,99059.65,0.0,2.71,0,99062.36,2019,1,23,31,0,0.0
23,2019-01-24,24,99062.36,0.0,2.71,0,99065.07,2019,1,24,31,0,0.0
24,2019-01-25,25,99065.07,0.0,2.71,0,99067.78,2019,1,25,31,0,0.0
25,2019-01-26,26,99067.78,0.0,2.71,0,99070.49,2019,1,26,31,0,0.0
26,2019-01-27,27,99070.49,0.0,2.71,0,99073.20,2019,1,27,31,0,0.0
27,2019-01-28,28,99073.20,0.0,2.71,0,99075.91,2019,1,28,31,0,0.0
28,2019-01-29,29,99075.91,0.0,2.71,0,99078.62,2019,1,29,31,0,0.0
29,2019-01-30,30,99078.62,0.0,2.71,0,99081.33,2019,1,30,31,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,2020-12-02,337,78481.50,0.0,4.30,0,78485.80,2020,12,2,31,1,0.0
702,2020-12-03,338,78485.80,0.0,4.30,0,78490.10,2020,12,3,31,1,0.0
703,2020-12-04,339,78490.10,0.0,4.30,0,78494.40,2020,12,4,31,1,0.0
704,2020-12-05,340,78494.40,0.0,4.30,0,78498.70,2020,12,5,31,1,0.0
705,2020-12-06,341,78498.70,0.0,4.30,0,78503.00,2020,12,6,31,1,0.0
706,2020-12-07,342,78503.00,0.0,4.30,0,78507.30,2020,12,7,31,1,0.0
707,2020-12-08,343,78507.30,0.0,4.30,0,78511.60,2020,12,8,31,1,0.0
708,2020-12-09,344,78511.60,0.0,4.30,0,78515.90,2020,12,9,31,1,0.0
709,2020-12-10,345,78515.90,0.0,4.30,0,78520.20,2020,12,10,31,1,0.0
710,2020-12-11,346,78520.20,0.0,4.30,0,78524.50,2020,12,11,31,1,0.0
711,2020-12-12,347,78524.50,0.0,4.30,0,78528.80,2020,12,12,31,1,0.0
712,2020-12-13,348,78528.80,0.0,4.30,0,78533.10,2020,12,13,31,1,0.0
713,2020-12-14,349,78533.10,0.0,4.30,0,78537.40,2020,12,14,31,1,0.0
714,2020-12-15,350,78537.40,0.0,4.30,0,78541.70,2020,12,15,31,1,0.0
715,2020-12-16,351,78541.70,0.0,4.30,0,78546.00,2020,12,16,31,1,0.0
716,2020-12-17,352,78546.00,0.0,4.30,0,78550.30,2020,12,17,31,1,0.0
717,2020-12-18,353,78550.30,0.0,4.30,0,78554.60,2020,12,18,31,1,0.0
718,2020-12-19,354,78554.60,0.0,4.30,0,78558.90,2020,12,19,31,1,0.0
719,2020-12-20,355,78558.90,0.0,4.30,0,78563.20,2020,12,20,31,1,0.0
720,2020-12-21,356,78563.20,0.0,4.30,0,78567.50,2020,12,21,31,1,0.0
721,2020-12-22,357,78567.50,0.0,4.31,0,78571.81,2020,12,22,31,1,0.0
722,2020-12-23,358,78571.81,0.0,4.31,0,78576.12,2020,12,23,31,1,0.0
723,2020-12-24,359,78576.12,0.0,4.31,0,78580.43,2020,12,24,31,1,0.0
724,2020-12-25,360,78580.43,0.0,4.31,0,78584.74,2020,12,25,31,1,0.0
725,2020-12-26,361,78584.74,0.0,4.31,0,78589.05,2020,12,26,31,1,0.0
726,2020-12-27,362,78589.05,0.0,4.31,0,78593.36,2020,12,27,31,1,0.0
727,2020-12-28,363,78593.36,0.0,4.31,0,78597.67,2020,12,28,31,1,0.0
728,2020-12-29,364,78597.67,0.0,4.31,0,78601.98,2020,12,29,31,1,0.0
729,2020-12-30,365,78601.98,0.0,4.31,0,78606.29,2020,12,30,31,1,0.0
730,2020-12-31,366,78606.29,0.0,4.31,0,78610.60,2020,12,31,31,1,1.0